#!/usr/bin/env bun
/**
 * 配置 Git hooks：pull 后自动执行 link-skills
 */

import { existsSync, mkdirSync, writeFileSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(scriptDir, '..');
const hooksDir = path.join(projectRoot, '.git', 'hooks');

const POST_MERGE_CONTENT = `#!/bin/sh
# Auto-generated by setup-git-hooks - do not edit
# 每次 git pull 后自动同步 skills 软连接
cd "$(git rev-parse --show-toplevel)" && bun run link-skills
`;

function main(): void {
  if (!existsSync(path.join(projectRoot, '.git'))) {
    console.log('未检测到 .git 目录，跳过 Git hooks 配置');
    return;
  }

  if (!existsSync(hooksDir)) {
    mkdirSync(hooksDir, { recursive: true });
  }

  const hookPath = path.join(hooksDir, 'post-merge');
  writeFileSync(hookPath, POST_MERGE_CONTENT, { mode: 0o755 });
  console.log('已配置 Git hook: post-merge (git pull 后执行 link-skills)');
}

main();
